#ifndef _CONFIGURATION_HPP
#define _CONFIGURATION_HPP

#define TEN_BIT_VALUE_FOR_16_8_V 1024
#define MOTOR_STEP_PER_TURN 200
#define MOTOR_FORWARD_DIR HIGH
#define MOTOR_BACKWARD_DIR LOW

#endif /* _CONFIGURATION_HPP */
